bapp/urls.py
from django.contrib import admin
from .import views
from django.urls import path,include
from bapp.views import base,main,detail,form,rent_book,returned,return_view,cancel_view

app_name='bapp'
urlpatterns = [
    path('',base,name='base'),
    #path('cancel/',cancel,name=cancel),
    path('detail/<int:book_id>/', detail, name='detail'),
    path('order/<int:book_id>/', views.order, name='order'),
    
    path('main/',main,name='main'),
    path('form/',form,name='form'),
    path('success/',return_view,name='return_view'),
    path('cancel/',cancel_view,name='cancel_view'),
    path('rent-book/<int:book_id>/', rent_book, name='rent_book'),
    path('returned/',returned,name='returned'),
    path('book/<int:book_id>/add_review/', views.add_review, name='add_review'),
    path('review/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('review/<int:review_id>/delete/', views.delete_review, name='delete_review'),
    path('book/<int:pk>/', views.book_detail, name='book_detail'),
    path('accounts/', include('django.contrib.auth.urls')),
   
   


]

bookstore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView

from jet import urls as jet_urls


app_name='bapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bapp.urls')),
    path('account/',include('registration.backends.default.urls')),
    path('jet/', include(jet_urls, 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('account/login/', LoginView.as_view(success_url='bapp:main'), name='login'),
    path('paypal/', include("paypal.standard.ipn.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Books(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500, default=None)
    price = models.FloatField(null=True, blank=True)
    img = models.ImageField(upload_to="")
    book_available = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
#----------------------------------------------------------------------
class Buy(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Add this line
    product = models.ForeignKey(Books, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}_{self.product.title}_{self.id}"

from django.db import models
from django.contrib.auth.models import User



class Cart(models.Model):
    cart_id = models.CharField(max_length=15)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()
    timestamp = models.DateTimeField(auto_now=True)
    product = models.ForeignKey(Books, on_delete=models.PROTECT)

    def __str__(self):
        return self.product.title

class User(models.Model):
    username = models.CharField(max_length=55)  # Change 'user' to 'username'
    email_id = models.EmailField()
    city = models.CharField(max_length=20)
    date_joined = models.DateField()

    def __str__(self):
        return self.username  # Corrected to 'self.username'


class BookRent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    rented_date = models.DateTimeField(auto_now_add=True)
    return_date = models.DateTimeField(null=True, blank=True)
    # You can add more fields like due_date, fine_amount, etc., as per your requirements
    
    def __str__(self):
        return f"{self.user.username} rented {self.book.title}" if self.user else "No user assigned"


from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100)
    # Other fields related to the user profile

    def __str__(self):
        return self.user.username
   
# models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    comment = models.TextField()
    rating = models.IntegerField()
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.username} - {self.book.title} - {self.timestamp}"



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100)
    # Other fields related to the user profile

    def __str__(self):
        return self.user.username

bapp/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
class User(forms.Form):

    Username=forms.CharField(max_length=55)
    Bookname=forms.CharField(max_length=55)
    email_id=forms.EmailField()
    city=forms.CharField(max_length=20)
    date=forms.DateField()
    def __init__(self,request,*args,**kwargs):
        self.request=request
        super(User,self).__init__(*args,**kwargs)


class CartForm(forms.Form):
    quantity=forms.IntegerField(initial=1)
    product_id=forms.IntegerField(widget=forms.HiddenInput)

from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'rating']

bapp/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import  Books, User, BookRent,Buy
from django.shortcuts import render
from django.http import HttpResponse
from bapp import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib import messages
#from django. import index
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Books, User, BookRent,Buy
from paypal.standard.forms import PayPalPaymentsForm
from django.urls import reverse

from django.contrib import messages
from django.views import View

from django.http import JsonResponse
import json
from django.views.generic import DetailView







def base(request):
 # Pass the query string back to the template to display in the search input
    

    return render(request, 'base.html')

def main(request):

    b=Books.objects.all()
    if request.GET.get('q'):
      query = request.GET.get('q') 
      b = Books.objects.filter(title__icontains=query)  

   
    context={'b':b,}
    return render(request,'main.html',context)
from django.db.models import Avg

def detail(request, book_id):
    book = get_object_or_404(Books, pk=book_id)
    reviews = Review.objects.filter(book=book)
    context = {'d': book,'reviews': reviews}
    return render(request, 'detail.html', context)


def form(request):
    return render(request,'form.html')

def returned(request):
    return render(request,'returned.html')





#============================rent longic

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import Books, BookRent
from django.utils import timezone
from django.contrib.auth.models import User

def rent_book(request, book_id):
    book = get_object_or_404(Books, pk=book_id)

    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        city = request.POST.get('city')
        return_date = request.POST.get('return_date')
        book_name = request.POST.get('title')

        
        
        # Update book availability
        book.book_available = False
        book.save()

        messages.success(request, f"You have successfully rented '{book.title}'. You can now take the book.")
        return redirect('bapp:main')  # Redirect after successful renting

    return render(request, 'rent_book.html', {'book': book})


def calculate_fine(return_date):
    # Example: Calculate fine as $5 per day for late return
    days_overdue = (timezone.now().date() - return_date).days
    fine_amount = 5 * days_overdue
    return fine_amount

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import Books

def book_detail(request, book_id):
    book = Books.objects.get(id=book_id)
    return render(request, 'book_detail.html', {'object': book})

#==========================================return book
import uuid
from django.contrib.auth.decorators import login_required

@login_required
def order(request, book_id):
    try:
        book_id = int(book_id)
    except ValueError:
        # Handle the case where book_id is not a valid integer
        return HttpResponse("Invalid book ID")

    # Get the current user instance
    current_user = request.user

    # Get the book instance based on the provided book_id
    book = Books.objects.get(pk=book_id)

    # Calculate the total amount for the selected book
    total_amount = book.price

    # Create an order for the current user and the selected book
    order = Buy.objects.create(user=current_user, product=book, quantity=1, price=total_amount)
    order.save()

    # PayPal payment dictionary
    paypal_dict = {
        "business": "sb-l7r2e28145955@business.example.com",
        "amount": total_amount,
        "invoice": str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('bapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('bapp:cancel_view')),
        "custom": "premium_plan",
    }

    # Create the PayPal form
    form = PayPalPaymentsForm(initial=paypal_dict)

    # Render the order page with the form
    context = {"form": form, "total": total_amount}
    return render(request, "order.html", context)

def return_view(request):
    return render(request,'done.html')
def cancel_view(request):
    return render(request,'cancel.html')




from django.shortcuts import render
from .models import Review

def book_detail(request, book_id):
    book = Books.objects.get(pk=book_id)
    reviews = Review.objects.filter(book=book)
    is_available = book.book_available
    context = {
        'book': book,
        'reviews': reviews,
        'is_available': is_available
        
    }
    book = get_object_or_404(Books, pk=book)
    # Rest of your view logic goes here
    return render(request, 'book_detail.html', {'book': book})

# views.py

from django.shortcuts import get_object_or_404, redirect
from .models import Review
from .forms import ReviewForm

def edit_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('book_detail', book_id=review.book.id)
    else:
        form = ReviewForm(instance=review)
    return render(request, 'edit_review.html', {'form': form, 'review': review})

def delete_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if request.method == 'POST':
        review.delete()
        return redirect('book_detail', book_id=review.book.id)
    return render(request, 'delete_review.html', {'review': review})
from django.shortcuts import render, get_object_or_404, redirect
from .models import Books, Review
from .forms import ReviewForm

def add_review(request, book_id):
    book = get_object_or_404(Books, pk=book_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.book = book

            # Use request.user inside the is_valid block
            review.user = request.user if request.user.is_authenticated else None

            review.save()
            return redirect('bapp:main')
    else:
        form = ReviewForm()
    return render(request, 'add_review.html', {'form': form, 'book': book})

bapp/templates/add_review.html
{% extends 'base.html'%}
{% block content %}
<style>
    body{
      background-image: url(https://eskipaper.com/images/blurry-wallpaper-hd-1.jpg);
      background-size: cover;
      
      
    }

  p{
    color: bisque;
  }

    .form {
      width: 300px;
      margin: 0 auto;
      margin-top: 70px;
      padding: 30px;
      background-color:rgba(55, 55, 55, 0.546);
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.539);
      color: #f0e5e5;
    }

    form {
      
      text-align: center;
    }
  </style>
<center>
    <!-- add_review.html -->

<h2>Add Review for {{ book.title }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Review</button>
</form>

</center>
{% endblock %}

bapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">   
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script>// Smooth scrolling for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
          e.preventDefault();
  
          document.querySelector(this.getAttribute('href')).scrollIntoView({
              behavior: 'smooth'
          });
      });
  });</script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
<style>
  * {
  scroll-behavior: smooth;
}
body {
    font-family: 'Arial', sans-serif;
    margin: 0;
    padding: 0;
    scroll-behavior: smooth; }
  * {
  margin: auto;
  padding: auto;
  box-sizing: border-box;
}

/* Styling the header and navigation */
header {
  background-color: #333;
  color: #fff;
  padding: 10px 20px;
}

nav ul {
  list-style: none;
}

nav ul li {
  display: inline;
  margin-right: 20px;
}

nav ul li a {
  color: #fff;
  text-decoration: none;
}

/* Styling sections */
section {
  height: 75vh; /* Adjust to fit your design */
  display: flex;
  justify-content: center;
  align-items: center;
  scroll-margin-top: 25px; /* Adjust to offset fixed header height */
}

section:nth-child(odd) {
  background-color: #f0f0f0;
}

section:nth-child(even) {
  background-color: #e0e0e0;
}


html {
  scroll-behavior:smooth;
}
  *{
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    box-sizing: border-box;
  }
    body{
      background-image: url(https://img.freepik.com/premium-photo/white-wood-texture-that-is-very-textured-has-light-brown-color_769803-1890.jpg?w=1380);
      background-size: cover;
    }
      body{
    height: 100vh;
    align-items: center;
    justify-content: center;
}

    .btn-warning {
      border-radius: 25%;
    }
       a 
       { 
        color: bisque;
       }
</style>
<body>
  
  {% csrf_token %}
  
    <!-- Bootstrap Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000000a5;">
      <div class="container-fluid">
          <a class="navbar-brand" href="#">
              <img src="https://img.freepik.com/premium-vector/monogram-rb-br-logo_477193-208.jpg?size=626&ext=jpg&ga=GA1.1.1663448891.1700729226&semt=sph" alt="" width="35" height="35" class="d-inline-block align-text-top">
              Bookstore
          </a>
          <form class="form-inline my-2 my-lg-0 mr-auto" method="GET" action="{% url 'bapp:main' %}">
            <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" aria-label="Search">
           <div> <button class="btn btn-outline-success" type="submit">Search</button></div>
        </form>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo03">
          
        
              
          <div class="border-radius=25%">
              <ul class="navbar-nav">
                  {% if not user.is_authenticated %}
                      <li class="nav-item">
                          <a class="btn btn-primary mx-2" href="{% url 'auth_login' %}">Login</a>
                      </li>
                      <li class="nav-item">
                          <a class="btn btn-primary mx-2" href="{% url 'registration_register' %}">Register</a>
                      </li>
                  {% else %}
                      <li class="nav-item">
                          <a class="btn btn-danger mx-2" href="{% url 'auth_logout' %}">Logout</a>
                      </li>
                  {% endif %}
                  <div class="col-md-1">
                    <a  class="btn btn-warning mx-auto"  href="/admin/">Staff</a>
                  </div>
                </ul>
          </div>
      </div>
  </nav>


    



      {% block content %}
      
      <br>
      <br>
      <br>
      <div class="container">
        <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="2000">
              <img src="https://readjumpscares.files.wordpress.com/2023/05/june-2023-new-horror.png?w=1200" class="d-block w-100" alt="..." style="height: 400px; object-fit: cover;">
              <div class="carousel-caption d-none d-md-block">
                <h5>Welcome to Bookstore</h5>
                <p>Click login/regisert to explore</p>
              </div>
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="https://assets.gqindia.com/photos/6327592852fd9998eca36af3/16:9/w_2560%2Cc_limit/Queer-Horror-Novels.jpg" class="d-block w-100" alt="..." style="height: 400px; object-fit: cover;">
              <div class="carousel-caption d-none d-md-block">
                <h5>explore the books</h5>
                <p>Click login/regisert to explore</p>
              </div>
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="https://render.fineartamerica.com/images/rendered/default/poster/8/4/break/images/artworkimages/medium/1/classic-english-literature-books-tim-gainey.jpg" class="d-block w-100" alt="..." style="height: 400px; object-fit: cover;">
              <div class="carousel-caption d-none d-md-block">
                <h5>Get ready by new stock</h5>
                <p>Click login/regisert to explore.</p>
              </div>
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
      <br>
      <br>
    
    <center>
      <div class="col-md-4">
        <div class="content-center">
          <div class="row-cols-1">
            {% if not user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>&nbsp;
                <a class="btn btn-outline-primary" href="{% url 'registration_register' %}">Register</a>
                <br>
                <br>
                <div class="col-md-1">
                  <a class="btn btn-warning mx-auto"  href="/admin/">Staff</a>
                </div>
                {% else %}
                <a href="{% url 'bapp:main' %}" class="btn btn-outline-success">Click to continue</a>
                {% endif %}
              </div>
          </div>     
      </div>
      <br>
   
    </center>
      
      {% endblock %}


      

</body>
</html>

bapp/templates/cancel.html
<!DOCTYPE html>
<html lang="en">
    <style>
        h2{
            color: crimson;
        }
        body{
            background-color: rgb(0, 0, 0);
            align-items: center;
            

        }
    </style>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <br><br>
    <br><br>
    <br>
    <center>
        <img height="150px" src="https://cdn.pixabay.com/animation/2023/09/14/14/44/14-44-18-961_512.gif" alt="" class="background-size">
        <h2>Payment canceled!</h2>
        <br>
        <br>
        <a href="{% url 'bapp:main' %}" class="btn btn-outline-dark" role="button">click to return home</a>
    </center>
</body>
</html>

bapp/templates/cart.html
{% extends 'base.html'%}
{% block content %}
<table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total cost</th>
      </tr>
    </thead>
    <tbody>
        {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td>{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
       <td>
         <form action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-outline-danger" type="submit" name="delete" value="delete">
        </form>
    </td>
      </tr>
     {% endfor %}
    </tbody>
  </table>
  {% endblock %}
<!-- <center><h4 class="btn-outline-success"><br>Total:{{t}}<br></h4></center>
<a href="{% url 'bapp:index' %}"><h6 class="btn btn-outline-danger">back</h6></a>
&nbsp;&nbsp;&nbsp;
 <center><br><a href="{% url 'bapp:order' %}" class="btn btn-light">  ORDER  </a><br></center> -->










 

bapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<br>
<style>
  p{
    font-style: italic;
    font-size: medium;
    font-weight:600
  }
  div{
    align-items:normal
  }
</style>
<a href="{% url 'bapp:main' %}" class="btn btn-outline-dark" role="button">Back</a>
<br>
<br>
<br>

<center>
<div class="card mb-3" style="max-width: 1250px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{ d.img.url }}" class="card-img">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h4 class="card-title">{{ d.title }}</h4>
        <p class="card-text">Price: ${{ d.price }}</p>
        <p class="card-text" name="new">{{ d.description }}</p>
        <br>
        <br>
        <br>
        <br>
        {% if  d.book_available %}
          <a  href="{% url 'bapp:rent_book' d.id %}" class="btn btn-primary">Rent</a>
          <a href="{% url 'bapp:order' d.id %}" class="btn btn-warning" role="button">Buy</a>
        {% else%}
          <div class="mx-auto" style="width: 340px;">
            <h4 class="text-danger">Sorry, this book is temporarily unavailable</h4>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>


{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
</center>
<a class="btn btn-outline-primary" href="{% url 'bapp:add_review' d.id %}">Add a Review</a>

<!-- Display reviews -->
<h2>Reviews</h2>
{% for review in reviews %}
    <ul class="list-group-item">
        <p>{{ review.comment }}</p>
        <p>Rating: {{ review.rating }}</p>
        <small class="text-muted">Date: {{ review.timestamp|date:"F d, Y" }}</small>
        <!-- Add edit/delete links for admin -->
    </ul>
{% empty %}
    <p>No reviews yet.</p>
{% endfor %}

{% endblock %}

bapp/templates/main.html
{% extends 'base.html' %}
{% block content %}

<style>
    /* body
    {
       background-image: url(https://images.saymedia-content.com/.image/t_share/MTkzOTUzODU0MDkyNjE3MjIx/particlesjs-examples.gif);
    } */
    body {
        height: 100vh;
        align-items: center;
        justify-content: center;}

    .content >*{
        font-size: 20px;
        color:beige;
        position: fixed;
        background-position: 2%;
        font-style: oblique;
        background-image: url(https://cdn.svgator.com/images/2022/06/use-svg-as-background-image-particle-strokes.svg);
        width:1498px; position:relative;margin:auto
        

    }

    </style> 
<div class="">
    <br>
    <br>
    <br>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-4 g-4">
            {% for book in b %}
            <div class="col">
                <div class="card h-70">
                    <img src="{{ book.img.url }}" class="card-img-top" alt="..." height="500" width="240" style="object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <p>Book ID: {{ book.id }}</p>
                        <p class="card-text">Price: ${{ book.price }}</p>
                        {% if book.book_available %}
                            <li class="text-primary">Available</li>
                        {% else %}
                            <li class="text-danger">Out of Stock!</li>
                        {% endif %}<br>
                       
                        <a href="{% url 'bapp:detail' book.id %}" class="btn btn-warning">Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<br>
<section id="section1">
<center>
<div class="background-image">
 <div class="container-fluid footer-first">
    <div class="container-fluid footer-second">
        <div class="content">
            <div class="col-md-4">
                <h4><font class="object-fit">Contact us</font></h4>
                <h7>Email:</h7><p>jacksparrow3466@gmail.com</p>
                <h8>Created by Bookcraft team</h8>
                <h7>for enquiry purpose contact:<p>Above email </p></h7>
                <br>
                <p>Created for testing purpose not the real webpage</p>
                <p>For copyright purpose contact the above email</p>
                <br>
                <p>®©All rights are not reserved</p>
                <br>

            </div>

        </div>

    </div>
</div>
</center>
</section>
{% endblock %}